### ISSUE TITLE
bloc_demo 无法运行成功

### ISSUE THREAD

**Issue by yikwing** [OpenFlutter/Flutter-Notebook#1]
希望大佬有时间能出一个详细一点的bloc教程,类似bottombar那种,普及中国flutter发展

**Comment by Vadaski** [comment]
收到，我会尽快修复此bug。
普及说不上，尽我的一份努力吧哈哈。
详细BLoC教程已在计划当中，具体请关注我的掘金博客~

**Comment by Vadaski** [comment]
已修复，请copy最新版本查看，使用时请将api替换成最新版本，谢谢！

**Comment by fg2q1q3q** [comment]
最新版本应该也没修复吧，我的flutter已经升级到最新仍然报错，报错主要是因为_subject变量没有定义

**Comment by Vadaski** [comment]
感谢指出，现已修复。
你重新pull一下应该就可以运行了

**Comment by chenqincheng** [comment]
I/flutter ( 7942): The following NoSuchMethodError was thrown building TopPage(dirty):
I/flutter ( 7942): The getter 'bLoC' was called on null.
I/flutter ( 7942): Receiver: null
I/flutter ( 7942): Tried calling: bLoC

报错指向：static CountBLoC of(BuildContext context) => (context.inheritFromWidgetOfExactType(BlocProvider) as BlocProvider).bLoC;
