### ISSUE TITLE
CupertinoActionSheet 点击底部弹窗崩溃报错

### ISSUE THREAD

**Issue by RedSevenMale** [OpenFlutter/Flutter-Notebook#10]
release_preview2 中的cupertino_action_sheet_action_demo.dart 运行报错

**Comment by Vadaski** [comment]
感谢反馈，该bug已修复

**Comment by RedSevenMale** [comment]
大佬，请问sliver_demo中TabBarView加载的第一个MyHomePage（）中能和顶部APPbar一起联动吗，第二个第三个TabBarView都可以联动

**Comment by Vadaski** [comment]
感谢反馈。
review之后我发现sliver这个例子我做的不太好，大家实际上都是希望sliverappbar和下面联动的，需要使用custom scroll view，但是tabbar和tab view不是一个sliver，我之后将重新上传sliver相关demo
