### ISSUE TITLE
有没有关于webview的相关例子呢...

### ISSUE THREAD

**Issue by djkloop** [OpenFlutter/Flutter-Notebook#12]
在app内调用webview这方面的例子有么....看官网貌似还不支持...

**Comment by Vadaski** [comment]
现在暂时还没有计划处webview的demo，但是你可以在这里关注flutter_web_view的发布进度🤨
https://pub.dartlang.org/packages/flutter_web_view#-changelog-tab-

**Comment by djkloop** [comment]
@Vadaski 好吧，感觉webview能偷懒少写一些代码23333...谢谢作者提供的这么多demo，真的是良心23333....
