### ISSUE TITLE
有这种例子吗？就是底部有个textfield，键盘弹出后顶在键盘上面的效果

### ISSUE THREAD

**Issue by 370966584** [OpenFlutter/Flutter-Notebook#14]

**Comment by Vadaski** [comment]
类似im那种？

**Comment by 370966584** [comment]
> 类似im那种？

对 聊天页面或者贴吧那样的底部有输入框的情况

**Comment by Vadaski** [comment]
近期出一个

**Comment by 370966584** [comment]
> 近期出一个

好的多谢

**Comment by Vadaski** [comment]
https://github.com/OpenFlutter/Flutter-Notebook/tree/master/mecury_project/example/animation_challenge
做完啦🤣
