### ISSUE TITLE
http.dart

### ISSUE THREAD

**Issue by fg2q1q3q** [OpenFlutter/Flutter-Notebook#15]
找不到http.dart,然后我使用dio替代，结果报错，不清楚哪里出了问题，帮忙解决下，下拉刷新项目，代码如下
```
    Dio http = new Dio();
    final Response<String> response = await http.get('http://dog.ceo/api/breeds/image/random');
    if (response.statusCode == 200) {
      setState(() {
        images.add(json.decode(response.data)['message']);
      });
    } else {
      throw Exception('Failed to load images');
    }

```

**Comment by Vadaski** [comment]
贴出下你的报错信息吧，或者手动添加http包依赖也是可以的

**Comment by fg2q1q3q** [comment]
之所以没有继续依赖http包是因为翻遍你的项目也没找到有引用这个依赖，并且网上查到相关资料很少，唯一一个官网还打不开。所以选用了更出名的dio。编译没有错误，只有运行的时候会直接崩溃，你可以按照上面代码试验下，崩溃信息没有太大用处（我是自己起的项目从其他页面跳转到这个下拉刷新demo页面，跳转之前好好地，一点跳转就崩溃）

**Comment by CaiJingLong** [comment]
http是dart官方出品的http请求库,代码质量很高

依赖添加可以查看下面的连接
https://pub.dartlang.org/packages/http#-installing-tab-

中文镜像
https://pub.flutter-io.cn/packages/http#-installing-tab-

**Comment by Vadaski** [comment]
崩溃的原因可能在于你的资源没有释放，检查一下controller之类的是否在dispose中被手动释放

**Comment by fg2q1q3q** [comment]
多谢，dio应该也没问题，崩溃的原因已找到，因为我自己的主页和你下拉刷新demo的page名字一样，所以跳转的时候崩溃
