### ISSUE TITLE
slider_screen 这个例子backgroundColor属性 需要用Color包一层

### ISSUE THREAD

**Issue by djkloop** [OpenFlutter/Flutter-Notebook#16]
demo中的写法报错，
![image](https://user-images.githubusercontent.com/21050914/49310056-2f83ff00-f518-11e8-90bc-d4a5840ad049.png)
改成这样就好了
![image](https://user-images.githubusercontent.com/21050914/49310042-27c45a80-f518-11e8-8d82-db686fac01e3.png)

**Comment by Vadaski** [comment]
感谢提出，这是第三方依赖版本不同所导致的，我之后会升级到最新版

**Comment by Vadaski** [comment]
intro_slider最新版就是使用0xff203152的呢，刚才去pub也确认过啦，你升级到最新版应该就可以了
