### ISSUE TITLE
希望出一个登录退出MyApp()切换路由堆栈的Demo

### ISSUE THREAD

**Issue by 370966584** [OpenFlutter/Flutter-Notebook#19]

**Comment by Vadaski** [comment]
能在清楚描述一下吗，是做登陆模块？
退出登陆之后重新打开app再次弹出登陆页面？

**Comment by 370966584** [comment]
> 能在清楚描述一下吗，是做登陆模块？
> 退出登陆之后重新打开app再次弹出登陆页面？

是这样，打开app如果没有登录主界面是一个登录页，登录完成后跳转到主界面由bottomNavigationBar和PageView组成，在某个界面有个退出操作，退出后主页面重新变成一个登录页.
现在有个问题，退出和登录路由跳转有点问题，使用 pushAndRemoveUntil退出后是黑屏(如果直接使用push在主页pop后会退到登录页)，使用run(Myapp)第一次可以退出成功，第二次退出就没有反应了，不知道哪的问题
