### ISSUE TITLE
你好，请问有只支持camera的库吗

### ISSUE THREAD

**Issue by fg2q1q3q** [OpenFlutter/Flutter-Notebook#20]

**Comment by Vadaski** [comment]
flutter团队提供了这个camera库 -> https://pub.dartlang.org/packages/camera，我不太明白你想要的只支持camera的库是什么意思>_<?

**Comment by fg2q1q3q** [comment]
不好意思，我已经通过调用原生的方法实现了。因为我的APP只有拍照没有选照片的需求。官方的camera我也看过了参考价值不大，相对而言还是自己调原生最方便。
