### ISSUE TITLE
 Another exception was thrown: NoSuchMethodError: The getter 'bLoC' was called on null.

### ISSUE THREAD

**Issue by jp1017** [OpenFlutter/Flutter-Notebook#27]
使用的scope的bloc，

```
class BlocProvider extends InheritedWidget{
  final CountBloc bLoC = CountBloc();

  BlocProvider({Key key, Widget child}) : super(key: key, child: child);

  @override
  bool updateShouldNotify(_) => true;

  static CountBloc of(BuildContext context) =>
      (context.inheritFromWidgetOfExactType(BlocProvider) as BlocProvider).bLoC;
}
```

移植到自己项目报错：

>I/flutter: Another exception was thrown: NoSuchMethodError: The getter 'bLoC' was called on null.

![screenshot_2019-02-27-13-10-37-600_add2flutter](https://user-images.githubusercontent.com/7868514/53467569-c0c02e80-3a91-11e9-9cc1-22760c614dbc.png)

**Comment by jp1017** [comment]
现在用的单例提供bloc

**Comment by jp1017** [comment]
找到问题了，`BlocProvider` 要先调用

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      child: MaterialApp(
        title: 'scoped',
        theme: ThemeData.dark(),
        home: TopPage(),
      ),
    );
  }
}
```

**Comment by mirkancal** [comment]
After navigation I get the same error. Do I have to wrap my MaterialApp with BlocProvider?

**Comment by nrooban** [comment]
HI guys, this kind of The getter 'id' was called on null. happens because of when you do HotReload.

To reproduce this
============
1. Restart the app again(Check the app wether its working fine without doing any modification in hot-reload)
2. If works fine, do some text or icon change and let hot-reload.
3. Now do the testing again it will fail with 'The getter 'id' was called on null.'

I too waiting for the solution..

**Comment by souravroyrickey** [comment]
I am getting same error but while navigating to a page from a drawer. Below is the code but after number of attempts unable to find solution.

Navigator.push(context,MaterialPageRoute(builder: (context){
    final nbloc = BlocProvider.of<NotificationBloc>(context);
    return BlocProvider(child: NotificationPage(), bloc: nbloc);
}));
