### ISSUE TITLE
能不能启动其他APP

### ISSUE THREAD

**Issue by tedgo** [OpenFlutter/Flutter-Notebook#28]
能不能启动其他APP

**Comment by Vadaski** [comment]
你是说的类似分享这种功能吗

**Comment by Jemair** [comment]
应该是 schema 跳转
用这个库就可以了  https://pub.dartlang.org/packages/url_launcher#-readme-tab-

**Comment by Jemair** [comment]
我发了一个 pr @tedgo 
https://github.com/OpenFlutter/Flutter-Notebook/pull/32
