### ISSUE TITLE
能否请教下，如何在cupertino的组件下实现一个类似material的tabbar...

### ISSUE THREAD

**Issue by djkloop** [OpenFlutter/Flutter-Notebook#37]
能否请教下，如何在cupertino的组件下实现一个类似material的tabbar...有什么思路吗...看官方material里面的tabbar实现好复杂啊- -。看的头好晕

**Comment by Vadaski** [comment]
最新 stable 版本出来了一个 platform widget，可以试试用这个来做

**Comment by Vadaski** [comment]
因无人回复故关闭此issue，如有需要请再次打开，谢谢！
