### ISSUE TITLE
写demo的时候blocprovider，的of返回值是null

### ISSUE THREAD

**Issue by CYZZ** [OpenFlutter/Flutter-Notebook#39]
(context.inheritFromWidgetOfExactType(BlocProvider) as BlocProvider)
在BlocProvider类中的of函数调用的时候报错，提示结果为null，无法调用属性.bloc.

**Comment by Vadaski** [comment]
信息比较少，我说一下我的推断
应该是没有在祖先节点正确获取有bloc_provider节点的context的缘故，可以看一下这篇然后对照代码检查一下https://juejin.im/entry/5c66cd0751882562654ab750

**Comment by Vadaski** [comment]
因无人回复故关闭此issue，如有需要请再次打开，谢谢！
