### ISSUE TITLE
项目导入as非常多的报错

### ISSUE THREAD

**Issue by fg2q1q3q** [OpenFlutter/Flutter-Notebook#4]

**Comment by Vadaski** [comment]
你需要先下载依赖😁

**Comment by Vadaski** [comment]
如果您的问题已经解决了的话，请在这里告诉我一下~😋
谢谢

**Comment by Vadaski** [comment]
请问有正确下载依赖吗，每个子项目依赖都需要get一遍

Barry <notifications@github.com> 于2018年9月30日周日 下午5:17写道：

**Comment by fg2q1q3q** [comment]
你好，其他例子通过package get下载依赖后确实可以了，但是flutter_auto_json_parsing这个例子不行，报错如下
```
The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.
Because flutter_auto_json_parsing depends on build_runner >=0.1.1 <=0.9.1 which requires SDK version >=1.9.1 <2.0.0-∞, version solving failed.
pub get failed (1)
```
可能依赖库版本与sdk版本不兼容，请问这些依赖库版本在哪里可以查到

**Comment by Vadaski** [comment]
https://juejin.im/entry/5b89618351882542da339883

建议使用这篇文章的办法，可以解决大多数版本不兼容的问题😁

**Comment by fg2q1q3q** [comment]
你好，该问题我已解决，不过导入项目运行过程发现另外两个问题，还望指教：
1、运行项目根目录下的main.dart报错(虽然知道是编码问题，但不清楚如何处理)
```
Finished with error: FormatException: Bad UTF-8 encoding 0xb4 (at offset 120)
```
2、第一个例子（看注释应该是动画demo：正方形→圆形）在酷派Y71（android5.0）上运行后，只有一个大白板上面显示一个蓝色正方形，既没有MaterialApp主题应有的titlebar也没有变圆形的动画效果，请问是代码就是这么写的还是其他什么原因导致的

**Comment by Vadaski** [comment]
1.bad utf8的错误原因有很多，解决方案也有所不同。根目录下这个我觉得不太影响，你可以选择忽略。也可以加个好友讨论下。

2.第二个例子是material的border radius失效，我也正在寻找原因，目前已经用decoration的radius替代material，你重新pull后应该能看到正确的效果。

希望能够帮助到你哈

**Comment by fg2q1q3q** [comment]
bad utf-8的报错经查应该是example下很多项目导包使用了相对路径引起的，建议使用绝对路径，参阅https://github.com/flutter/flutter/issues/15793
