### ISSUE TITLE
勘误：keep_alive_demo中build方法须调用super.build

### ISSUE THREAD

**Issue by CCY0122** [OpenFlutter/Flutter-Notebook#40]
代码位置：mecury_project/example/keep_alive_demo/lib/keep_alive_demo.dart。
根据AutomaticKeepAliveClientMixin的注释文档，子类的build方法中必须调用super.build

**Comment by Vadaski** [comment]
感谢订正

ccy <notifications@github.com> 于2019年8月10日周六 下午3:24写道：

**Comment by Vadaski** [comment]
fixed
