### ISSUE TITLE
导入AndroidStudio报错

### ISSUE THREAD

**Issue by fangzhouguang** [OpenFlutter/Flutter-Notebook#42]
D:\flutterProject\Flutter-Notebook-master\Flutter-Notebook-master\mecury_project\example: no pubspec.yaml found

**Comment by Vadaski** [comment]
hi fangzhouguang ，这里的 example 是总目录文件夹，所以是运行不起来的，所有样例在 example 的下一级目录，每个目录分别对应了一个可运行的 Flutter Demo，请分别尝试运行，thanks！

**Comment by Vadaski** [comment]
我认为本 issue 已 fixed，故关闭。若有需要请再次打开，谢谢

**Comment by fangzhouguang** [comment]
所有demo需要一个个的去get package，累死了，哈哈

**Comment by AureliusPatiens** [comment]
本质上是让你建一个新的项目包
