### ISSUE TITLE
工具目录有个文件，有问题，无法Checkout.

### ISSUE THREAD

**Issue by Aaron009** [OpenFlutter/Flutter-Notebook#43]
![1](https://user-images.githubusercontent.com/3838050/69510133-80d19d80-0f76-11ea-8d3a-ba37a4b1e194.png)
这个文件有问题。需要删除。

**Comment by Vadaski** [comment]
已修复，谢谢你的反馈哦 😃

Aaron009 <notifications@github.com> 于2019年11月25日周一 上午11:27写道：
