### ISSUE TITLE
在provider_example中，如何初始化状态数据？

### ISSUE THREAD

**Issue by yuzhewo** [OpenFlutter/Flutter-Notebook#45]
provider中如何初始化数据，不可能每次打开APP都会从0开始增进，如何结合持久化存储与状态初始化做的数据的保持与加载，有没有什么建议？

**Comment by AureliusPatiens** [comment]
话说这个库里面有案例的

**Comment by Vadaski** [comment]
数据持久化可以在 Model 初始化的时候去内存中尝试读取一次数据，然后异步加载，比如用户 Model，打开应用闪屏页这段时间就应该是把本地数据加载到内存中来。状态管理只是在内存中进行操作，同步数据与界面。provider 现在的 demo 还有点简陋，我最近更新一下。

**Comment by Vadaski** [comment]
已更新单页面提供者供参考。本项目尽量是想做一些简单 demo，实现单一功能，这个 issue 中的问题实际上是数据本地化问题结合 provider，所以就不加入 provider demo 了。
