### ISSUE TITLE
有關於dispose方法

### ISSUE THREAD

**Issue by dev-weiqi** [OpenFlutter/Flutter-Notebook#46]
想請教您在 count_bloc 中的 dispose() 有把 subject 給close，
但是好像沒有人去呼叫這個 method ，這樣不會造成 Leak 嗎？

**Comment by Vadaski** [comment]
好问题！理论上一个 stream 不再被使用的话就应当关闭掉，所以我们必须在 count_bloc 中重写 dispose 方法。但是在这个例子中我们所有页面都依赖于这个 stream，其实是找不到一个机会去 dispose 掉的，所以我在 demo 中没有释放。一些信息，比如 user_bloc 这样的随时需要获取的，可能需要长期存在的 bloc 可以这么做，如果你有机会释放的话，请及时释放；）
